[package]
name = "hello-world"
version = "0.1.0"
edition = "2024"

[dependencies]
gl = "0.14.0"
glutin = "0.32.3"
glutin-winit = "0.5.0"
nalgebra-glm = "0.20.0"
raw-window-handle = "0.6.2"
winit = "0.30.12"
